---
- name: Install tmpreaper
  apt:
    name: tmpreaper
    state: present

- name: Remove note about tmpreaper security
  lineinfile:
    path: "/etc/tmpreaper.conf"
    line: "# see /usr/share/doc/tmpreaper/README.security.gz"
    state: absent

- name: setup tmpreaper cron for Galaxy tmp
  cron:
    name: "tmpreaper_clean_tmp"
    user: "{{ galaxy_user.name }}"
    hour: "1"
    weekday: "0"
    job: "/usr/sbin/tmpreaper --mtime --dirmtime {{ max_tmpfile_age | default('7d') }} {{ galaxy_mutable_data_dir }}/tmp"

- name: setup tmpreaper cron for Galaxy jobs dir
  cron:
    name: "tmpreaper_clean_jobs"
    user: "{{ galaxy_user.name }}"
    hour: "2"
    weekday: "0"
    job: "/usr/sbin/tmpreaper --mtime --dirmtime {{ max_tmpfile_age | default('7d') }} {{ galaxy_root }}/jobs"

- name: setup pgcleanup script
  cron:
    name: "pgcleanup_{{ item.index }}"
    user: "{{ galaxy_user.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    weekday: "{{ item.weekday }}"
    job: >-
      source {{ galaxy_venv_dir }}/bin/activate &&
      {{ __galaxy_server_dir }}/scripts/cleanup_datasets/pgcleanup.py -c {{ galaxy_config_dir }}/galaxy.yml {{ item.command }}
  loop:
    - { index: "1", weekday: "0", hour: "3", minute: "0", command: "-o 30 delete_userless_histories" }
    - { index: "2", weekday: "0", hour: "4", minute: "0", command: "-o 30 delete_exported_histories" }
    - { index: "3", weekday: "0", hour: "4", minute: "30", command: "-o 30 purge_deleted_users" }
    - { index: "4", weekday: "1", hour: "3", minute: "0", command: "-o 30 purge_deleted_histories" }
    - { index: "5", weekday: "1", hour: "4", minute: "0", command: "-o 60 purge_deleted_hdas" }
    - { index: "6", weekday: "2", hour: "3", minute: "0", command: "-o 90 purge_datasets" }
