---
- name: Install tmpreaper
  apt:
    name: tmpreaper
    state: present

- name: Remove note about tmpreaper security
  lineinfile:
    path: "/etc/tmpreaper.conf"
    line: "# see /usr/share/doc/tmpreaper/README.security.gz"
    state: absent

- name: setup tmpreaper cron for Galaxy tmp
  cron:
    name: "tmpreaper_clean_tmp"
    user: "{{ galaxy_user.name }}"
    hour: "1"
    weekday: "0"
    job: "/usr/sbin/tmpreaper --mtime --dirmtime {{ max_tmpfile_age | default('7d') }} {{ galaxy_mutable_data_dir }}/tmp"

- name: setup tmpreaper cron for Galaxy jobs dir
  cron:
    name: "tmpreaper_clean_jobs"
    user: "{{ galaxy_user.name }}"
    hour: "2"
    weekday: "0"
    job: "/usr/sbin/tmpreaper --mtime --dirmtime {{ max_tmpfile_age | default('7d') }} {{ galaxy_root }}/jobs"

- name: setup gxadmin log dir
  file:
    path: '{{ galaxy_mutable_data_dir }}/gxadmin_logs'
    state: directory
    owner: '{{ galaxy_user.name }}'
    
- name: setup gxadmin galaxy cleanup script
  cron:
    name: "gx_galaxy_cleanup"
    user: "{{ galaxy_user.name }}"
    hour: "{{ gx_galaxy_cleanup_hour | default(3) }}"
    minute: "{{ gx_galaxy_cleanup_minute | default(0) }}"
    weekday: "{{ gx_galaxy_cleanup_weekday | default(0) }}"
    job: >-
      GALAXY_LOG_DIR={{ galaxy_mutable_data_dir }}/gxadmin_logs
      GALAXY_ROOT={{ galaxy_root }}
      GALAXY_CONFIG_FILE={{ galaxy_config_dir}}/galaxy.yml gxadmin galaxy cleanup {{ gx_cleanup_days | default(30) }}